# Generated by Django 4.1.5 on 2023-02-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('groupchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='conversation',
            new_name='room',
        ),
    ]
